### ISSUE TITLE
Adding line break during run time

### ISSUE THREAD

**Issue by Shaurya-tech** [skyrpex/RichText#18]
Hi, excellent work.

I am writing a textbox for my program and all works smoothly except now I want to be able to add a line break to the text when I press the return key. I've tried doing: `enteredRaw.push_back("\\n");` when return key is pressed, all elements from enteredRaw get put into a string s and used like thus:
```
sfe::RichText text(font);
text << sf::Text::Regular << sf::Color::Black <<  s;
```
however the rendered string is on the same line

![image](https://user-images.githubusercontent.com/31845301/37564513-989dd576-2aeb-11e8-981c-e31dec994daa.png)

When checking the output of the string and even what is rendered on screen, both have "\n" in them, so what am I doing wrong?

**Comment by StAlRuth** [comment]
Hi,

I see you've escaped the backslash in your push_back call, which means that the string contains a literal "\n" instead of a newline and appears to cause the issue you describe.

You should try removing the second backslash and see if that works.  If not, please provide a more complete minimal example so I or someone else can test it further.
